config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    put :like, on: :member
  end

  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    get "check_email_duplicacy", to: "registrations#check_email_duplicacy"
  end

  resources :comments, only: [:create, :destroy]

  root "home#index"
  post "/", to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_nested_set scope: %i[commentable_id commentable_type]

  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :body, presence: true

  def self.build_from(obj, user_id, comment)
    new(commentable: obj, body: comment, user_id: user_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  acts_as_taggable_on :tags
  acts_as_commentable

  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true
  validates :archive, inclusion: { in: [true, false] }

  scope :order_by_date, -> { order(created_at: :desc) }
  scope :archived,      -> { where(archive: true) }
  scope :non_archived,  -> { where(archive: false) }
  scope :find_posts,    ->(query) { joins(:tags).where("lower(title) LIKE :query OR lower(body) LIKE :query OR tags.name LIKE :query", query: "%#{query.downcase}%") }
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable, :trackable

  before_validation do
    self.first_name = first_name.to_s.squish.titleize
    self.last_name = last_name.to_s.squish.titleize
  end

  has_many :posts, dependent: :destroy

  validates :first_name, :last_name, presence: true, length: { maximum: 255 }

  def full_name
    "#{first_name} #{last_name}"
  end

  def initial
    "#{first_name[0]}#{last_name[0]}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    comment_hash = params[:comment]
    obj = comment_hash[:commentable_type].constantize.find(comment_hash[:commentable_id])
    @comment = Comment.build_from(obj, current_user.id, comment_hash[:body])

    if @comment.save
      render "create"
    else
      render js: "alert('Something happened wrong..!!');"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    if @comment.destroy
      render "delete"
    else
      render js: "alert('Something happened wrong..!!');"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:tag].present?
      posts = Post.non_archived.tagged_with(params[:tag])
    elsif params[:search].present?
      posts = Post.non_archived.find_posts(params[:search])
    else
      posts = Post.non_archived
    end

    @pagy, @posts = pagy_countless(posts.includes(:tags).order_by_date, link_extra: 'data-remote="true"')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def index
    if params[:tag].present?
      posts = current_user.posts.tagged_with(params[:tag])
    else
      posts = current_user.posts
    end

    @pagy, @posts = pagy_countless(posts.includes(:tags).order_by_date, link_extra: 'data-remote="true"')
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comment_threads.includes(:user).order(created_at: :desc)
    @new_comment = Comment.build_from(@post, current_user.id, "") if user_signed_in?

    redirect_to root_path, flash: { danger: "You tried to access unauthorized post." } if @post.archive? && @post.user_id != current_user&.id
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post, flash: { success: "Your Post has been successfully created." }
    else
      render "new"
    end
  end

  def edit
    post
  end

  def update
    if post.update(post_params)
      redirect_to post, flash: { success: "Your Post has been successfully updated." }
    else
      render "edit"
    end
  end

  def destroy
    post.destroy
    redirect_to post, flash: { success: "Your Post has been successfully deleted." }
  end

  def like
    @post = Post.find(params[:id])
    @voted_for = current_user.voted_for?(@post)

    if @voted_for
      @post.unliked_by(current_user)
    else
      @post.liked_by(current_user)
    end

    render layout: false
  end

  private

  def post
    @post ||= Post.find(params[:id])
    return @post if @post.user_id == current_user.id

    redirect_to root_path, flash: { danger: "You tried to access unauthorized post." }
  end

  def post_params
    params.require(:post).permit(:title, :body, :archive, :tag_list)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def check_email_duplicacy
    user = User.find_by(email: params[:email])

    if user
      render status: :unprocessable_entity, json: { message: t("invalid_email") }
    else
      render status: :ok, json: { message: t("valid_email") }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def full_title(page_title = "")
    base_title = t("page_title")

    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def flash_message_prefix(message_type)
    case message_type
    when "success" then t("success_alert_prefix")
    when "info"    then t("info_alert_prefix")
    when "warning" then t("warning_alert_prefix")
    when "danger"  then t("danger_alert_prefix")
    else ""
    end
  end

  def message_type(message_type)
    case message_type
    when "notice" then t("notice_message_type")
    when "alert"  then t("alert_message_type")
    else message_type
    end
  end
end

app/views/comments/_comment.html.erb
<div class="row" id="comment_<%= comment.id %>">
  <div class="col-sm-12 col-md-6">
    <b><%= comment.user.full_name %></b>
    <%= link_to "Delete", comment_path(comment), method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: "text-danger ml-2" if current_user == comment.user %>
  </div>

  <div class="col-sm-12 col-md-6 text-md-right">
    <span class="text-muted">Commented <%= time_ago_in_words(comment.created_at) %> ago</span>
  </div>

  <div class="col-sm-12 col-md-12">
    <p><%= comment.body %></p>
  </div>
</div>

app/views/comments/_comments.html.erb
<% comments.each do |comment| %>
  <div class="row" id="comment_<%= comment.id %>">
    <div class="col-sm-12 col-md-6">
      <b><%= comment.user.full_name %></b>
      <%= link_to "Delete", comment_path(comment), method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: "text-danger ml-2" if current_user == comment.user %>
    </div>

    <div class="col-sm-12 col-md-6 text-md-right">
      <span class="text-muted">Commented <%= time_ago_in_words(comment.created_at) %> ago</span>
    </div>

    <div class="col-sm-12 col-md-12">
      <p><%= comment.body %></p>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="mt-3 mb-4">
  <%= form_for comment, remote: true do |f| %>
    <%= f.hidden_field :commentable_id %>
    <%= f.hidden_field :commentable_type %>

    <div class="form-group">
      <%= f.text_area :body, class: "form-control", required: true, placeholder: "Write your comment here...", rows: 2 %>
    </div>

    <div class="form-group">
      <%= f.submit "Comment", class: "btn btn-primary", data: { disable_with: "Saving..." } %>
    </div>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#new_comment_block').append("<%= j(render 'comment', comment: @comment)%>");
$('#comment_body').val('');

app/views/comments/delete.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/destroy.js.erb
$('#commentdiv').html("<%= j (render 'comments/comment', comments: @comments) %>");
$('.commentbox').val('.commentbox').val('');

app/views/comments/edit.js.erb
$('#commentform').html("<%= j (render 'comments/form', comment: @comment, post: @post) %>");
$('.commentbox').focus();
$('.commentbox').val('.commentbox').val("<%= @comment.content %>");

app/views/comments/update.js.erb
$('#commentform').html("<%= escape_javascript( render 'comments/form', comment: @post.comments.build, post: @post) %>")
$('.commentbox').val('.commentbox').val('');
$('.commentbox').focus();
$('#commentdiv').html("<%= j (render 'comments/comment', comments: @comments) %>");

app/views/home/_posts.html.erb
<% @classes = ["primary", "secondary", "success", "danger", "warning", "info", "dark"] %>

<% @posts.each do |post| %>
  <div class="card mb-3">
    <div class="card-body">
      <% if post.archive? %>
        <span class="badge badge-danger mb-2">Archived</span>
      <% end %>

      <h5 class="card-title"><%= link_to truncate(post.title, length: 50), post_path(post) %></h5>
      <p class="card-text"><%= truncate(post.body, length: 400) %></p>

      <div class="mb-3">
        <% post.tags.each_with_index do |tag, index| %>
          <span class="badge badge-<%= @classes[index % 7] %>"><%= tag.name %></span>
        <% end %>
      </div>

      <div class="row">
        <div class="col-sm-12 col-md-6">
          <% if user_signed_in? %>
            <%=
                link_to current_user.voted_for?(post) ? '<i class="fas fa-thumbs-up like-icon" title="Dislike"></i>'.html_safe : '<i class="far fa-thumbs-up like-icon" title="Like"></i>'.html_safe,
                        like_post_path(post),
                        method: :put,
                        remote: true,
                        class: "like-btn"
            %>
          <% end %>

          <span class="likes-count"><span id="like_count_<%= post.id %>"><%= post.get_upvotes.size %></span> Likes</span>
        </div>

        <div class="col-sm-12 col-md-6 text-md-right">
          <span class="text-muted">Posted <%= time_ago_in_words(post.created_at) %> ago</span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_search.html.erb
<%= form_tag root_path, method: :post, class: "form-inline" do %>
  <%= text_field_tag :search, params[:search], class: "form-control mr-3 mb-3", placeholder: "Search..." %>
  <%= submit_tag "Search", class: "btn btn-primary mb-3" %>
<% end %>

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<% @classes = ["primary", "secondary", "success", "danger", "warning", "info", "dark"] %>
<% @liked_posts = current_user&.votes %>

<section class="mb-4 d-flex justify-content-between">
  <h3>Post Album</h3>

  <span>
    <%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
  </span>
</section>

<%= render "search" %>

<div class="row">
  <div id="user_posts" class="col-sm-12 col-md-9">
    <%= render "posts" %>
  </div>

  <div class="col-sm-12 col-md-3">
    <h4>Most popular tags:</h4>

    <div class="card">
      <div class="card-body">
        <% ActsAsTaggableOn::Tag.most_used(20).each_with_index do |tag, index| %>
          <%= link_to root_path(tag: tag.name), class: "badge badge-#{@classes[index % 7]}" do %>
            <%= tag.name %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="auto_next_link">
  <%= render "shared/auto_incremental_pagy" %>
</div>

app/views/home/index.js.erb
$('#user_posts').append("<%= j(render 'posts')%>");
$('#auto_next_link').html("<%= j(render 'shared/auto_incremental_pagy') %>")

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type(message_type) %> alert-dismissible fade show flash-alert m-4" role="alert">
    <strong><%= flash_message_prefix(message_type(message_type)) %></strong> <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container">
    <%= link_to "Blog Post", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle initial-dropdown" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.initial %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Post History", posts_path, class: "dropdown-item" %>
              <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title><%= full_title(yield(:title)) %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="//code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container" id="main_content">
      <div class="card main-content-card">
        <%= render "layouts/flash_messages" %>

        <div class="card-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= render "shared/error", resource: @post %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", autofocus: true, required: true, placeholder: "Post Title", maxlength: 255 %>
  </div>

  <div class="form-group">
    <%= f.label :body, "Body" %>
    <%= f.text_area :body, class: "form-control", required: true, placeholder: "Write your post here...", rows: 10 %>
  </div>

  <div class="form-group">
    <%= f.label :tag_list, "Tag Lists" %>
    <%= f.text_field :tag_list, value: @post.tag_list.split(" ").join(", "), class: "form-control", required: true, placeholder: "Tags" %>
    <small id="tagListHelp" class="form-text text-muted">Tags are "," separated string.</small>
  </div>

  <div class="form-group custom-control custom-checkbox">
    <%= f.check_box :archive, class: "custom-control-input" %>
    <%= f.label :archive, class: "custom-control-label" %>
  </div>

  <div class="form-group">
    <%= f.submit yield(:button_text), class: "btn btn-primary", data: { disable_with: "Saving..." } %>
    <%= link_to "Cancel", @post.new_record? ? root_path : posts_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<% @classes = ["primary", "secondary", "success", "danger", "warning", "info", "dark"] %>

<% @posts.each do |post| %>
  <div class="card mb-3">
    <div class="card-body">
      <% if post.archive? %>
        <span class="badge badge-danger mb-2">Archived</span>
      <% end %>

      <h5 class="card-title"><%= truncate(post.title, length: 50) %></h5>
      <p class="card-text"><%= truncate(post.body, length: 400) %></p>

      <div class="mb-3">
        <% post.tags.each_with_index do |tag, index| %>
          <span class="badge badge-<%= @classes[index % 7] %>"><%= tag.name %></span>
        <% end %>
      </div>

      <section class="row">
        <div class="col-sm-12 col-md-6">
          <span class="text-muted">Posted <%= time_ago_in_words(post.created_at) %> ago</span>
        </div>

        <div class="col-sm-12 col-md-6 text-md-right">
          <%= link_to "View", post_path(post), class: "text-primary" %> |
          <%= link_to "Edit", edit_post_path(post), class: "text-info" %> |
          <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }, class: "text-danger" %>
        </div>
      </section>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>
<% provide(:button_text, "Update Post") %>

<div class="row justify-content-center">
  <div class="col-sm-12 col-md-7 mb-4">
    <h3 class="text-center">Edit Post</h3>
  </div>

  <div class="col-sm-12 col-md-7">
    <%= render "form" %>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Post History") %>
<% @classes = ["primary", "secondary", "success", "danger", "warning", "info", "dark"] %>

<h2 class="mb-4">Post History</h2>

<div class="row">
  <div id="user_posts" class="col-sm-12 col-md-9">
    <%= render "posts" %>
  </div>

  <div class="col-sm-12 col-md-3">
    <h4>Most popular tags:</h4>

    <div class="card">
      <div class="card-body">
        <% ActsAsTaggableOn::Tag.most_used(20).each_with_index do |tag, index| %>
          <%= link_to posts_path(tag: tag.name), class: "badge badge-#{@classes[index % 7]}" do %>
            <%= tag.name %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="auto_next_link">
  <%= render "shared/auto_incremental_pagy" %>
</div>

app/views/posts/index.js.erb
$('#user_posts').append("<%= j(render 'posts')%>");
$('#auto_next_link').html("<%= j(render 'shared/auto_incremental_pagy') %>")

app/views/posts/like.js.erb
$('#like_count_<%= @post.id %>').html("<%= @post.get_upvotes.size %>");

<% if @voted_for %>
  $('#like_count_<%= @post.id %>').closest('div').find('.like-btn').html('<i class="far fa-thumbs-up like-icon" title="Like"></i>');
<% else %>
  $('#like_count_<%= @post.id %>').closest('div').find('.like-btn').html('<i class="fas fa-thumbs-up like-icon" title="Dislike"></i>');
<% end %>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>
<% provide(:button_text, "Create Post") %>

<div class="row justify-content-center">
  <div class="col-sm-12 col-md-7 mb-4">
    <h3 class="text-center">New Post</h3>
  </div>

  <div class="col-sm-12 col-md-7">
    <%= render "form" %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<% classes = ["primary", "secondary", "success", "danger", "warning", "info", "dark"] %>

<div class="row">
  <div class="col-sm-12 col-md-9">
    <% if @post.archive? %>
      <span class="badge badge-danger mb-2">Archived</span>
    <% end %>

    <h2 class="mb-3"><%= @post.title %></h2>

    <div class="mb-3">
      <% @post.tags.each_with_index do |tag, index| %>
        <span class="badge badge-<%= classes[index % 7] %>"><%= tag.name %></span>
      <% end %>
    </div>

    <p><%= @post.body %></p>

    <div class="row">
      <div class="col-sm-12 col-md-6">
        <% if user_signed_in? %>
          <%=
              link_to current_user.voted_for?(@post) ? '<i class="fas fa-thumbs-up like-icon"></i>'.html_safe : '<i class="far fa-thumbs-up like-icon"></i>'.html_safe,
                      like_post_path(@post),
                      method: :put,
                      remote: true,
                      class: "like-btn"
          %>
        <% end %>

        <span><span id="like_count_<%= @post.id %>"><%= @post.get_upvotes.size %></span> Likes</span>
      </div>

      <div class="col-sm-12 col-md-6 text-md-right">
        <span class="text-muted">Posted <%= time_ago_in_words(@post.created_at) %> ago</span>
      </div>
    </div>

    <% if user_signed_in? %>
      <%= render "comments/form", comment: @new_comment %>
    <% end %>

    <div class="comments-block">
      <h4 class="mb-4">Comments:</h4>
      <div id="new_comment_block"></div>
      <%= render "comments/comments", comments: @comments %>
    </div>
  </div>

  <div class="col-sm-12 col-md-3">
    <h4>You may like:</h4>

    <% @post.find_related_tags.first(10).each do |post| %>
      <%= link_to truncate(post.title, length: 30), post_path(post) %><br>
    <% end %>
  </div>
</div>

app/views/shared/_auto_incremental_pagy.html.erb
<%== pagy_next_link(@pagy, '', 'id="next_link" class="d-none"') %>

app/views/shared/_error.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <% resource.errors.full_messages.each.with_index(1) do |msg, index| %>
      <p class="mb-0">
        <%= index %>. <%= msg %>.
      </p>
    <% end %>
  </div>
<% end %>